site_name: AuxBot Documentation

repo_name: Auxtal/AuxBot-Python-Docs
repo_url: https://github.com/Auxtal/AuxBot-Python-Docs
edit_uri: ""

theme:
  favicon: assets/AuxBot.png
  logo: assets/AuxBot.png
  name: 'material'

  features:
    - header.autohide
    - navigation.tabs
    - navigation.sections

  palette:
    scheme: slate
    primary: red
    accent: white

markdown_extensions:
  - toc:
      permalink: true

copyright: Copyright Â© AuxBot 2021 All Rights Reserved